/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AstraRouteImport } from './routes/astra'
import { Route as AstrophysicsRouteImport } from './routes/astrophysics'
import { Route as ChemistryRouteImport } from './routes/chemistry'
import { Route as DataRouteImport } from './routes/data'
import { Route as ExperimentsRouteImport } from './routes/experiments'
import { Route as LaboratoryRouteImport } from './routes/laboratory'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as LabOrbitalMechanicsRouteImport } from './routes/lab/orbital-mechanics'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AstraRoute = AstraRouteImport.update({
  id: '/astra',
  path: '/astra',
  getParentRoute: () => rootRouteImport,
} as any)
const AstrophysicsRoute = AstrophysicsRouteImport.update({
  id: '/astrophysics',
  path: '/astrophysics',
  getParentRoute: () => rootRouteImport,
} as any)
const ChemistryRoute = ChemistryRouteImport.update({
  id: '/chemistry',
  path: '/chemistry',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRoute = DataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperimentsRoute = ExperimentsRouteImport.update({
  id: '/experiments',
  path: '/experiments',
  getParentRoute: () => rootRouteImport,
} as any)
const LaboratoryRoute = LaboratoryRouteImport.update({
  id: '/laboratory',
  path: '/laboratory',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const LabOrbitalMechanicsRoute = LabOrbitalMechanicsRouteImport.update({
  id: '/lab/orbital-mechanics',
  path: '/lab/orbital-mechanics',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/astra': typeof AstraRoute
  '/astrophysics': typeof AstrophysicsRoute
  '/chemistry': typeof ChemistryRoute
  '/data': typeof DataRoute
  '/experiments': typeof ExperimentsRoute
  '/laboratory': typeof LaboratoryRoute
  '/learn': typeof LearnRoute
  '/saved': typeof SavedRoute
  '/lab/orbital-mechanics': typeof LabOrbitalMechanicsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/astra': typeof AstraRoute
  '/astrophysics': typeof AstrophysicsRoute
  '/chemistry': typeof ChemistryRoute
  '/data': typeof DataRoute
  '/experiments': typeof ExperimentsRoute
  '/laboratory': typeof LaboratoryRoute
  '/learn': typeof LearnRoute
  '/saved': typeof SavedRoute
  '/lab/orbital-mechanics': typeof LabOrbitalMechanicsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/astra': typeof AstraRoute
  '/astrophysics': typeof AstrophysicsRoute
  '/chemistry': typeof ChemistryRoute
  '/data': typeof DataRoute
  '/experiments': typeof ExperimentsRoute
  '/laboratory': typeof LaboratoryRoute
  '/learn': typeof LearnRoute
  '/saved': typeof SavedRoute
  '/lab/orbital-mechanics': typeof LabOrbitalMechanicsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/astra'
    | '/astrophysics'
    | '/chemistry'
    | '/data'
    | '/experiments'
    | '/laboratory'
    | '/learn'
    | '/saved'
    | '/lab/orbital-mechanics'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/astra'
    | '/astrophysics'
    | '/chemistry'
    | '/data'
    | '/experiments'
    | '/laboratory'
    | '/learn'
    | '/saved'
    | '/lab/orbital-mechanics'
  id:
    | '__root__'
    | '/'
    | '/astra'
    | '/astrophysics'
    | '/chemistry'
    | '/data'
    | '/experiments'
    | '/laboratory'
    | '/learn'
    | '/saved'
    | '/lab/orbital-mechanics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AstraRoute: typeof AstraRoute
  AstrophysicsRoute: typeof AstrophysicsRoute
  ChemistryRoute: typeof ChemistryRoute
  DataRoute: typeof DataRoute
  ExperimentsRoute: typeof ExperimentsRoute
  LaboratoryRoute: typeof LaboratoryRoute
  LearnRoute: typeof LearnRoute
  SavedRoute: typeof SavedRoute
  LabOrbitalMechanicsRoute: typeof LabOrbitalMechanicsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/astra': {
      id: '/astra'
      path: '/astra'
      fullPath: '/astra'
      preLoaderRoute: typeof AstraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/astrophysics': {
      id: '/astrophysics'
      path: '/astrophysics'
      fullPath: '/astrophysics'
      preLoaderRoute: typeof AstrophysicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chemistry': {
      id: '/chemistry'
      path: '/chemistry'
      fullPath: '/chemistry'
      preLoaderRoute: typeof ChemistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiments': {
      id: '/experiments'
      path: '/experiments'
      fullPath: '/experiments'
      preLoaderRoute: typeof ExperimentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laboratory': {
      id: '/laboratory'
      path: '/laboratory'
      fullPath: '/laboratory'
      preLoaderRoute: typeof LaboratoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/orbital-mechanics': {
      id: '/lab/orbital-mechanics'
      path: '/lab/orbital-mechanics'
      fullPath: '/lab/orbital-mechanics'
      preLoaderRoute: typeof LabOrbitalMechanicsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AstraRoute: AstraRoute,
  AstrophysicsRoute: AstrophysicsRoute,
  ChemistryRoute: ChemistryRoute,
  DataRoute: DataRoute,
  ExperimentsRoute: ExperimentsRoute,
  LaboratoryRoute: LaboratoryRoute,
  LearnRoute: LearnRoute,
  SavedRoute: SavedRoute,
  LabOrbitalMechanicsRoute: LabOrbitalMechanicsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
